### ISSUE TITLE
Current version doesn't work with new cljs.core/UUID

### ISSUE THREAD

**Issue by franks42** [davesann/cljs-uuid#2]
Hi Dave,

I needed a random-uuid generator that works with the current clojurescript version.
Your current version didn't work with the updated cljs-version as of 11/27/12...

I took the liberty to copy part of your code to make it work (thanks!):
https://gist.github.com/4159427

As cljs.core/UUID defines a deftype with interface implementations, much of the pr-str and read-string can be left to the cljs.core/UUID implementation.

A random UUID generator for cljs will benefit the cljs-community!

If you will update your version, I'd be happy to use yours in the future.
If not, I will (reluctantly) maintain my version and make it available via github/clojars.

Thank, FrankS.

**Comment by davesann** [comment]
I will take a look. I did this before the UUID and tags were added to cljs. Happy to take your input
D

**Comment by davesann** [comment]
Updated. There were a couple of changes necessary. In particular converting the string buffer to a string. Without this - rereading written UUIDs do no match.
